# Generated by Django 2.0.6 on 2018-06-21 04:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_auto_20180619_0833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
    ]
