# Generated by Django 2.0.6 on 2018-06-24 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_auto_20180621_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Company'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ContractManager'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Section'),
        ),
    ]
