# Generated by Django 2.0.6 on 2018-07-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0004_auto_20180624_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='section_manager',
            field=models.CharField(default='Manager', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='section_manager_email',
            field=models.EmailField(default='Manager', max_length=254),
            preserve_default=False,
        ),
    ]
