# Generated by Django 2.0.6 on 2018-08-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0005_auto_20180723_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='comments',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
