# Generated by Django 2.0.6 on 2018-08-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0006_auto_20180803_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='comments',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
