# Generated by Django 2.0.6 on 2018-08-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0007_auto_20180803_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
    ]
