# Generated by Django 2.0.6 on 2018-06-24 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('notifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationstatus',
            name='notification_point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='notifier.NotificationPoint'),
            preserve_default=False,
        ),
    ]
