# Generated by Django 2.0.6 on 2018-06-24 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('notifier', '0002_notificationstatus_notification_point'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationstatus',
            options={'verbose_name_plural': 'Notification Statuses'},
        ),
        migrations.AlterField(
            model_name='notificationstatus',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Contract'),
        ),
    ]
