# Generated by Django 2.0.6 on 2018-06-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('notifier', '0003_auto_20180624_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationstatus',
            name='action_taken',
            field=models.BooleanField(default=False),
        ),
    ]
